var allImgPath = [
<<<<<<< HEAD
    "./images/IMG_0299.JPG",
    "./images/IMG_0463.JPG",
    "./images/IMG_1094.JPG",
    "./images/IMG_1161.JPG",
    "./images/IMG_1162.JPG",
    "./images/IMG_1534.JPG",
    "./images/IMG_1613.JPG",
    "./images/IMG_1614.JPG",
    "./images/IMG_1615.JPG",
    "./images/IMG_1616.JPG",
    "./images/IMG_1617.JPG",
    "./images/IMG_1618.JPG",
    "./images/IMG_1619.JPG",
    "./images/IMG_1645.JPG",
    "./images/IMG_1785.JPG",
    "./images/IMG_2367.JPG",
    "./images/IMG_2372.JPG",
    "./images/IMG_2437.JPG",
    "./images/IMG_2438.JPG",
    "./images/IMG_2550.JPG",
    "./images/IMG_2656.JPG",
    "./images/IMG_2752.JPG",
    "./images/IMG_2757.JPG",
    "./images/IMG_2758.JPG",
    "./images/IMG_2767.JPG",
    "./images/IMG_2768.JPG"
=======
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\591864d92f8730a56fef0429cdc57f00.jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (1).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (10).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (11).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (12).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (13).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (2).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (3).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (4).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (5).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (6).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (7).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (8).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg (9).jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\timg.jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\u=1365315108,236536146&fm=26&gp=0.jpg",
    "C:\\newSublime\\Sublime Text\\Code\\study-notes-css\\XHL\\照片墙\\images\\u=40217498,3509539114&fm=26&gp=0.jpg"
>>>>>>> 52ed89cbb88dee8a71fff0dad5595c9bbebadb6e
]